name: First practice HTML
on:
    push:
        branches:
            - master
    workflow_dispatch:
        inputs:
            content:
                description: 'Enter the content for the HTML file'
                required: true
                default: 'World'
                
jobs: 
    Explore-HTML:
        runs-on: ubuntu-latest
        steps: 
            - name: Checkout code
              uses: actions/checkout@v2 

            - name: aws credentials configuration
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
                aws-region: us-east-1
            - name: Login to Amazon ECR
              id: login-ecr
              uses: aws-actions/amazon-ecr-login@v2
              with:
                mask-password: 'false'

            -  name: Build, tag, and push image to Amazon ECR
               id: build-image
               run: 
                IMAGE_REPO_NAME=githubbucket91
                IMAGE_TAG=${{ github.event.inputs.image_tag }}
                ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
                REGION=$(aws configure get region)
                FULL_REPO_NAME="${ACCOUNT_ID}.dkr.ecr.${REGION}.amazonaws.com/${IMAGE_REPO_NAME}"
                  
                # Build the Docker image
                #do cker build -t $IMAGE_REPO_NAME.