name: Terraform AWS ECR Setup

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      content:
        description: 'Enter the content for ECR file'
        required: true
        default: 'World'

jobs:
  terraform:
    name: Terraform ECR Deployment
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Terraform AWS ECR Setup
        run: echo ""
      - name: aws credentials configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'false'

      -  name: Build, tag, and push image to Amazon ECR
         id: build-image
         run: 
          docker build -t bamendagirl .